### ISSUE TITLE
Use NUM_JOBS environment variable instead of hardcoding 4

### ISSUE THREAD

**Issue by jdm** [servo/osmesa-src#11]
In `build.rs`, we call make using `-j4`. We should do something like https://github.com/alexcrichton/cmake-rs/blob/a58c28876c2822c91e934e08b7f1abe819a530b8/src/lib.rs#L373 instead.

**Comment by yysung1123** [comment]
Hello! I would like to work in this issue!

**Comment by jdm** [comment]
Please do! Ask questions if anything is unclear!

**Comment by yysung1123** [comment]
If there is a NUM_JOBS env var, we use -j${NUM_JOBS}, otherwise we use -j4.
Is it right?

**Comment by jdm** [comment]
There should always be one, so it should be safe to use unwrap: http://doc.crates.io/environment-variables.html

**Comment by yysung1123** [comment]
I have sent a PR for this! Thanks for your guiding!
