### ISSUE TITLE
Build fails with LLVM master

### ISSUE THREAD

**Issue by emilio** [servo/osmesa-src#14]
See https://bugs.freedesktop.org/show_bug.cgi?id=98627.

Updating mesa or backporting https://patchwork.freedesktop.org/patch/120211/ should fix this.

**Comment by lemmabit** [comment]
I'm running Arch Linux, and the `llvm` package was recently updated to LLVM 4. I had to uninstall it and install `llvm39` before I could build Servo again. I hope this will be fixed soon.

**Comment by emilio** [comment]
This is basically #15 and https://github.com/servo/servo/pull/14584, but needs to go through the buildbots, which seem unhappy still.

**Comment by jyc** [comment]
Hi! Anything that could be done to help move this along? I've been running into this on Arch as well.
